const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const today=iso(new Date());
const defaults={cycleStart:today,plans:{},sessions:[],meals:[],templates:[
 {id:'lower',name:'Долна част · Сила',exercises:[['Hip Thrust',4],['Клек',4],['Румънска тяга',3],['Абдукция',3]]},
 {id:'upper',name:'Горна част · Тонус',exercises:[['Гребане',4],['Раменна преса',3],['Скрипец пред гърди',3],['Странично вдигане',3]]},
 {id:'glutes',name:'Седалище · Обем',exercises:[['Български клек',3],['Glute Bridge',4],['Кикбек',3],['Степ-ъп',3]]},
 {id:'recovery',name:'Мобилност и възстановяване',exercises:[['Разтягане',3],['Dead Bug',3],['Bird Dog',3]]}
]};
let state=JSON.parse(localStorage.getItem('fitflow-state')||'null')||structuredClone(defaults);
state.templates=state.templates||structuredClone(defaults.templates);state.plans=state.plans||{};state.sessions=state.sessions||[];state.meals=state.meals||[];state.drafts=state.drafts||{};state.sessions.forEach((s,i)=>s.id=s.id||`session-${s.date}-${i}`);
let selectedDate=today, calendarDate=new Date(), activeDate=today, activeTemplate=state.templates[0], activeSessionId=null, editingTemplateId=null, draftExercises=[];
const save=()=>localStorage.setItem('fitflow-state',JSON.stringify(state));
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const bgDate=d=>new Intl.DateTimeFormat('bg-BG',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'));
function cycleWeek(){return Math.max(1,Math.floor((new Date(today)-new Date(state.cycleStart))/604800000)+1)}
const completedOn=date=>state.sessions.some(s=>s.date===date);

function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view+'-view'));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent={today:'Днес',calendar:'Календар',workout:'Тренировка',food:'Хранене',stats:'Прогрес'}[view];if(view==='today')renderToday();if(view==='calendar')renderCalendar();if(view==='workout')startWorkout();if(view==='food')renderMeals();if(view==='stats')renderStats();scrollTo(0,0)}
$$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='workout'){activeDate=today;activeSessionId=null;draftExercises=[]}go(b.dataset.view)});$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));

function renderToday(){
 $('#today-date').textContent=bgDate(today);const week=cycleWeek();$('#cycle-week').textContent=Math.min(week,8);
 const plan=state.plans[today], template=state.templates.find(x=>x.id===plan);const done=state.sessions.some(x=>x.date===today&&(!template||!x.templateId||x.templateId===template.id));
 $('#today-workout').className='workout-card';
 $('#today-workout').innerHTML=`<small>${done?'ЗАВЪРШЕНА':'ИЗБЕРИ ЗА ДНЕС'}</small><select class="today-workout-select" id="today-workout-select"><option value="">Почивка</option>${state.templates.map(t=>`<option value="${t.id}" ${plan===t.id?'selected':''}>${t.name}</option>`).join('')}</select>${template?`<div class="meta"><span>${template.exercises.length} упражнения</span><span>${state.drafts[today]?'Има запазен запис':'≈ 50 мин'}</span></div>`:''}<button class="${template?'primary':'secondary'}" id="today-start" ${template?'':'disabled'}>${done?'Отвори и редактирай':state.drafts[today]?'Продължи тренировката':'Започни тренировка'}</button>`;
 $('#today-workout-select').onchange=e=>{const id=e.target.value;if(id)state.plans[today]=id;else delete state.plans[today];delete state.drafts[today];activeSessionId=null;save();renderToday()};
 $('#today-start').onclick=()=>{if(template){activeDate=today;activeTemplate=template;activeSessionId=(state.sessions.find(x=>x.date===today&&((x.templateId&&x.templateId===template.id)||(!x.templateId&&x.name===template.name)))||{}).id||null;draftExercises=[];go('workout')}};
 const meals=state.meals.filter(x=>x.date===today), sums=meals.reduce((a,m)=>({cal:a.cal+m.cal,p:a.p+m.p,c:a.c+m.c,f:a.f+m.f}),{cal:0,p:0,c:0,f:0});
 $('#calories-now').textContent=Math.round(sums.cal);$('#protein-now').textContent=Math.round(sums.p)+' g';$('#carbs-now').textContent=Math.round(sums.c)+' g';$('#fats-now').textContent=Math.round(sums.f)+' g';let pct=Math.min(100,Math.round(sums.cal/20));$('#calorie-percent').textContent=pct+'%';$('#calorie-bar').style.width=pct+'%';
 let dayPct=(done?60:0)+Math.min(40,Math.round(sums.cal/50));$('#day-ring').style.background=`conic-gradient(var(--lime) ${dayPct}%,rgba(255,255,255,.12) 0)`;$('#day-ring span').textContent=dayPct+'%';$('#today-summary').textContent=done?'Тренировката е отметната. Чудесна работа!':template?'Днешната тренировка те очаква.':'Планирай движение, което ти носи сила.';
}

function renderCalendar(){
 const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#month-label').textContent=new Intl.DateTimeFormat('bg-BG',{month:'long',year:'numeric'}).format(calendarDate);const first=(new Date(y,m,1).getDay()+6)%7, days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();let html='';
 for(let i=0;i<42;i++){let n,date,muted=false;if(i<first){n=prev-first+i+1;date=iso(new Date(y,m-1,n));muted=true}else if(i>=first+days){n=i-first-days+1;date=iso(new Date(y,m+1,n));muted=true}else{n=i-first+1;date=iso(new Date(y,m,n))}html+=`<button class="day ${muted?'muted ':''}${date===today?'today ':''}${date===selectedDate?'selected ':''}${state.plans[date]?'planned ':''}${completedOn(date)?'completed':''}" data-date="${date}">${n}</button>`}$('#calendar-grid').innerHTML=html;$$('.day').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar()});$('#selected-date').textContent=bgDate(selectedDate);$('#workout-select').innerHTML='<option value="">Почивка</option>'+state.templates.map(t=>`<option value="${t.id}" ${state.plans[selectedDate]===t.id?'selected':''}>${t.name}</option>`).join('');renderSelectedHistory();renderTemplateList();
}
$('#prev-month').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()};$('#next-month').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()};$('#save-plan').onclick=()=>{const v=$('#workout-select').value;if(v)state.plans[selectedDate]=v;else delete state.plans[selectedDate];save();renderCalendar();toast('Планът е запазен')};
$('#open-day-workout').onclick=()=>{const id=$('#workout-select').value||state.plans[selectedDate];const template=state.templates.find(t=>t.id===id);if(!template){toast('Първо избери тренировка');return}state.plans[selectedDate]=id;save();activeDate=selectedDate;activeTemplate=template;activeSessionId=(state.sessions.find(s=>s.date===selectedDate&&((s.templateId&&s.templateId===id)||(!s.templateId&&s.name===template.name)))||{}).id||null;draftExercises=[];go('workout')};

function sessionVolume(session){return session.exercises.reduce((sum,e)=>sum+e.sets.reduce((setSum,x)=>setSum+(+x.reps||0)*(+x.kg||0),0),0)}
function renderSelectedHistory(){const sessions=state.sessions.filter(s=>s.date===selectedDate);$('#selected-day-history').innerHTML=sessions.length?`<div class="section-title"><h2>История за деня</h2></div>`+sessions.map(s=>`<article class="panel history-card"><small>ЗАВЪРШЕНА ТРЕНИРОВКА</small><h3>${s.name}</h3><p>${s.exercises.length} упражнения · ${Math.round(sessionVolume(s)).toLocaleString('bg-BG')} kg обем</p><button class="secondary" data-open-session="${s.id}">Прегледай и редактирай</button></article>`).join(''):'';$$('[data-open-session]').forEach(b=>b.onclick=()=>{const session=state.sessions.find(s=>s.id===b.dataset.openSession);const template=state.templates.find(t=>t.id===session.templateId)||{id:session.templateId||`history-${session.id}`,name:session.name,exercises:session.exercises.map(e=>[e.name,e.sets.length])};activeDate=session.date;activeTemplate=template;activeSessionId=session.id;draftExercises=structuredClone(session.exercises);go('workout')})}

function renderTemplateList(){$('#template-list').innerHTML=state.templates.map(t=>`<div class="template-item"><div><b>${t.name}</b><span>${t.exercises.length} упражнения</span></div><div class="template-actions"><button class="edit-template" data-edit-template="${t.id}">Редактирай</button><button data-delete-template="${t.id}">Изтрий</button></div></div>`).join('');$$('[data-edit-template]').forEach(b=>b.onclick=()=>beginTemplateEdit(b.dataset.editTemplate));$$('[data-delete-template]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteTemplate;if(!confirm('Да изтрия ли тази тренировка?'))return;state.templates=state.templates.filter(t=>t.id!==id);Object.keys(state.plans).forEach(d=>{if(state.plans[d]===id)delete state.plans[d]});if(editingTemplateId===id)endTemplateEdit();save();renderCalendar();toast('Тренировката е изтрита')})}
function beginTemplateEdit(id){const template=state.templates.find(t=>t.id===id);if(!template)return;editingTemplateId=id;$('#new-workout-name').value=template.name;$('#new-workout-exercises').value=template.exercises.map(x=>`${x[0]} | ${x[1]}`).join('\n');$('#new-workout-sets').value=template.exercises[0]?.[1]||3;$('#create-workout').textContent='Запази промените';$('#cancel-workout-edit').classList.remove('hidden');$('#new-workout-name').focus();toast('Редактираш '+template.name)}
function endTemplateEdit(){editingTemplateId=null;$('#new-workout-name').value='';$('#new-workout-exercises').value='';$('#new-workout-sets').value=3;$('#create-workout').textContent='Създай тренировка';$('#cancel-workout-edit').classList.add('hidden')}
$('#cancel-workout-edit').onclick=endTemplateEdit;
$('#create-workout').onclick=()=>{const name=$('#new-workout-name').value.trim(),lines=$('#new-workout-exercises').value.split('\n').map(x=>x.trim()).filter(Boolean),count=Math.min(10,Math.max(1,+$('#new-workout-sets').value||3)),exercises=lines.map(line=>{const parts=line.split('|'),sets=Math.min(10,Math.max(1,+parts[1]||count));return[parts[0].trim(),sets]});if(!name){toast('Добави име на тренировката');return}if(!exercises.length||exercises.some(x=>!x[0])){toast('Добави поне едно упражнение');return}if(editingTemplateId){const template=state.templates.find(t=>t.id===editingTemplateId);template.name=name;template.exercises=exercises;save();endTemplateEdit();renderCalendar();toast('Тренировката е обновена');return}const id='custom-'+Date.now();state.templates.push({id,name,exercises});save();endTemplateEdit();renderCalendar();$('#workout-select').value=id;toast('Новата тренировка е създадена')};

function blankExercises(template){return template.exercises.map(([name,count])=>({name,sets:Array.from({length:count},()=>({reps:'',kg:''}))}))}
function persistDraft(){state.drafts[activeDate]={templateId:activeTemplate.id,exercises:structuredClone(draftExercises)};save()}
function startWorkout(){const planned=state.templates.find(t=>t.id===state.plans[activeDate]);if(planned&&!activeSessionId)activeTemplate=planned;const stored=state.drafts[activeDate],completed=activeSessionId?state.sessions.find(s=>s.id===activeSessionId):state.sessions.find(s=>s.date===activeDate&&((s.templateId&&s.templateId===activeTemplate.id)||(!s.templateId&&s.name===activeTemplate.name)));if(completed)activeSessionId=completed.id;if(!draftExercises.length)draftExercises=structuredClone(stored&&stored.templateId===activeTemplate.id?stored.exercises:completed?completed.exercises:blankExercises(activeTemplate));$('#active-workout-title').textContent=activeTemplate.name;$('#active-workout-date').textContent=bgDate(activeDate).toUpperCase();$('#finish-workout').textContent=completed?'Запази промените':'Завърши тренировката';renderExercises()}
function renderExercises(){$('#exercise-list').innerHTML=draftExercises.map((e,ei)=>`<article class="exercise-card"><div class="exercise-head"><div><small>УПРАЖНЕНИЕ ${ei+1}</small><h3>${e.name}</h3></div><button data-del-ex="${ei}">×</button></div>${e.sets.map((s,si)=>`<div class="set-row"><b>${si+1}</b><input inputmode="numeric" placeholder="повт." value="${s.reps}" data-reps="${ei}-${si}"><span>×</span><input inputmode="decimal" placeholder="кг" value="${s.kg}" data-kg="${ei}-${si}"><button data-del-set="${ei}-${si}">×</button></div>`).join('')}<button class="add-set" data-add-set="${ei}">+ Серия</button></article>`).join('');
 $$('[data-reps]').forEach(x=>x.oninput=()=>{let[a,b]=x.dataset.reps.split('-');draftExercises[a].sets[b].reps=x.value;persistDraft()});$$('[data-kg]').forEach(x=>x.oninput=()=>{let[a,b]=x.dataset.kg.split('-');draftExercises[a].sets[b].kg=x.value;persistDraft()});$$('[data-add-set]').forEach(x=>x.onclick=()=>{draftExercises[x.dataset.addSet].sets.push({reps:'',kg:''});persistDraft();renderExercises()});$$('[data-del-set]').forEach(x=>x.onclick=()=>{let[a,b]=x.dataset.delSet.split('-');draftExercises[a].sets.splice(b,1);persistDraft();renderExercises()});$$('[data-del-ex]').forEach(x=>x.onclick=()=>{draftExercises.splice(x.dataset.delEx,1);persistDraft();renderExercises()})}
$('#add-exercise').onclick=()=>{const name=prompt('Име на упражнението:');if(name){draftExercises.push({name,sets:[{reps:'',kg:''},{reps:'',kg:''},{reps:'',kg:''}]});persistDraft();renderExercises()}};$('#finish-workout').onclick=()=>{const valid=draftExercises.flatMap(e=>e.sets).some(s=>s.reps||s.kg);if(!valid){toast('Въведи поне една серия');return}const entry={id:activeSessionId||`session-${Date.now()}`,date:activeDate,templateId:activeTemplate.id,name:activeTemplate.name,exercises:structuredClone(draftExercises)};const index=activeSessionId?state.sessions.findIndex(s=>s.id===activeSessionId):state.sessions.findIndex(s=>s.date===activeDate&&((s.templateId&&s.templateId===activeTemplate.id)||(!s.templateId&&s.name===activeTemplate.name)));if(index>=0)state.sessions[index]=entry;else state.sessions.push(entry);activeSessionId=entry.id;delete state.drafts[activeDate];save();draftExercises=[];toast(index>=0?'Промените са запазени':'Тренировката е записана');setTimeout(()=>go(activeDate===today?'today':'calendar'),500)};

const foods=[
 {keys:['пилеш','пиле'],per:100,cal:165,p:31,c:0,f:3.6},{keys:['ориз'],per:100,cal:130,p:2.7,c:28,f:.3},{keys:['яйц'],per:60,cal:86,p:7.5,c:.4,f:5.7},{keys:['овес'],per:100,cal:389,p:17,c:66,f:7},{keys:['банан'],per:120,cal:107,p:1.3,c:27,f:.4},{keys:['кисело мляко','йогурт'],per:100,cal:61,p:3.5,c:4.7,f:3.3},{keys:['сьомга'],per:100,cal:208,p:20,c:0,f:13},{keys:['картоф'],per:100,cal:87,p:1.9,c:20,f:.1},{keys:['сирене'],per:100,cal:264,p:14,c:4,f:21},{keys:['хляб'],per:100,cal:265,p:9,c:49,f:3.2},{keys:['салата','зеленчу'],per:200,cal:60,p:3,c:12,f:1}];
let foodDraft=null;$('#analyze-food').onclick=()=>{const original=$('#food-description').value.trim(),text=original.toLowerCase();if(!text){toast('Опиши какво си хапнала');return}let totals={cal:0,p:0,c:0,f:0},found=0;foods.forEach(item=>{const key=item.keys.find(k=>text.includes(k));if(!key)return;found++;const before=text.slice(Math.max(0,text.indexOf(key)-15),text.indexOf(key)),match=before.match(/(\d+)\s*(?:г|гр|g)?\s*$/),amount=match?+match[1]:item.per,factor=amount/item.per;['cal','p','c','f'].forEach(k=>totals[k]+=item[k]*factor)});if(!found)totals={cal:450,p:20,c:50,f:18};foodDraft={date:today,text:original,type:$('#meal-type').value,...totals};$('#food-result').classList.remove('hidden');$('#result-calories').value=Math.round(totals.cal);$('#result-protein').value=Math.round(totals.p);$('#result-carbs').value=Math.round(totals.c);$('#result-fats').value=Math.round(totals.f)};
$('#save-food').onclick=()=>{foodDraft.cal=+$('#result-calories').value;foodDraft.p=+$('#result-protein').value;foodDraft.c=+$('#result-carbs').value;foodDraft.f=+$('#result-fats').value;foodDraft.id=Date.now();state.meals.push(foodDraft);save();$('#food-description').value='';$('#food-result').classList.add('hidden');renderMeals();toast('Храненето е добавено')};
function renderMeals(){const order=['Закуска','Обяд','Вечеря','Междинно хранене'];const meals=state.meals.filter(m=>m.date===today).sort((a,b)=>order.indexOf(a.type)-order.indexOf(b.type));$('#meal-list').innerHTML=meals.length?meals.map(m=>`<article class="meal-card"><div><span class="meal-type-badge">${m.type||'Хранене'}</span><h3>${m.text}</h3><p>${Math.round(m.cal)} kcal · P ${Math.round(m.p)} · C ${Math.round(m.c)} · F ${Math.round(m.f)}</p></div><button data-del-meal="${m.id}">×</button></article>`).join(''):'<article class="workout-card empty">Все още няма добавени хранения.</article>';$$('[data-del-meal]').forEach(b=>b.onclick=()=>{state.meals=state.meals.filter(m=>m.id!=b.dataset.delMeal);save();renderMeals()})}

function renderStats(){let volume=0,sets=0;state.sessions.forEach(s=>s.exercises.forEach(e=>e.sets.forEach(x=>{volume+=(+x.reps||0)*(+x.kg||0);if(x.reps||x.kg)sets++})));$('#stat-workouts').textContent=state.sessions.length;$('#stat-volume').textContent=Math.round(volume).toLocaleString('bg-BG')+' kg';$('#stat-meals').textContent=state.meals.length;$('#stat-sets').textContent=sets;const vols=state.sessions.slice(-7).map(s=>s.exercises.reduce((a,e)=>a+e.sets.reduce((b,x)=>b+(+x.reps||0)*(+x.kg||0),0),0)),max=Math.max(...vols,1);$('#volume-chart').innerHTML=vols.length?vols.map((v,i)=>`<div style="height:${Math.max(4,v/max*100)}%"><span>${i+1}</span></div>`).join(''):'<p class="hint">Завърши тренировка, за да видиш графиката.</p>';let w=cycleWeek();$('#cycle-message').textContent=w>=8?'Време е за нови упражнения':'Остават '+(8-w)+' седмици'}
$('#restart-cycle').onclick=()=>{state.cycleStart=today;save();renderStats();toast('Новият цикъл започна')};
$('#reset-btn').onclick=()=>{if(confirm('Искаш ли да изтриеш всички записани данни?')){state=structuredClone(defaults);save();renderToday();toast('Данните са изтрити')}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});renderToday();
